# Generated by Django 4.2.30 on 2026-08-05 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('user', models.CharField(default='System', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ComponentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='General', max_length=100)),
                ('binLocation', models.CharField(default='Bin A-1', max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('minThreshold', models.IntegerField(default=5)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Strict 8-character serial number (e.g. LS325044)', max_length=8, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('customer', models.CharField(blank=True, default='', max_length=150)),
                ('stage', models.CharField(choices=[('In Production / Fabrication', 'In Production / Fabrication'), ('Stock - Turkey', 'Stock - Turkey Warehouse'), ('Stock - USA', 'Stock - USA Warehouse'), ('Shipping to Customer (from Turkey)', 'Shipping to Customer (from Turkey)'), ('Shipping to Customer (from USA)', 'Shipping to Customer (from USA)'), ('Delivered to Customer', 'Delivered to Customer')], default='In Production / Fabrication', max_length=50)),
                ('targetLocation', models.CharField(blank=True, default='Stock - Turkey', max_length=100)),
                ('invoiceNo', models.CharField(blank=True, default='', max_length=50)),
                ('orderNo', models.CharField(blank=True, default='', max_length=50)),
                ('poNo', models.CharField(blank=True, default='', max_length=50)),
                ('quoteNo', models.CharField(blank=True, default='', max_length=50)),
                ('quoteAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amountPaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paymentStatus', models.CharField(choices=[('Unpaid', 'Unpaid / Invoice Sent'), ('Deposit Received', 'Deposit Received (50%)'), ('Fully Paid (100%)', 'Fully Paid (100%)'), ('Stock Listing', 'Stock Listing')], default='Unpaid', max_length=30)),
                ('cadVersion', models.CharField(blank=True, default='', max_length=50)),
                ('plcVersion', models.CharField(blank=True, default='', max_length=50)),
                ('bomRef', models.CharField(blank=True, default='', max_length=50)),
                ('prodStartDate', models.CharField(blank=True, default='', max_length=20)),
                ('prodEstFinishDate', models.CharField(blank=True, default='', max_length=20)),
                ('prodActualFinishDate', models.CharField(blank=True, default='Pending', max_length=20)),
                ('shipDate', models.CharField(blank=True, default='Pending', max_length=20)),
                ('deliveryDate', models.CharField(blank=True, default='Pending', max_length=20)),
                ('installationDate', models.CharField(blank=True, default='Pending', max_length=20)),
                ('installationEngineer', models.CharField(blank=True, default='Not Assigned', max_length=100)),
                ('installationSigned', models.BooleanField(default=False)),
                ('senderName', models.CharField(blank=True, default='ElectrospinTEK Logistics', max_length=100)),
                ('recipientName', models.CharField(blank=True, default='', max_length=100)),
                ('carrier', models.CharField(blank=True, default='ElectrospinTEK Freight', max_length=100)),
                ('trackingNo', models.CharField(blank=True, default='', max_length=50)),
                ('destination', models.CharField(blank=True, default='', max_length=150)),
                ('qcPassed', models.BooleanField(default=False)),
                ('qcDate', models.CharField(blank=True, default='Pending', max_length=20)),
                ('isStockOrder', models.BooleanField(default=False)),
                ('salesYear', models.CharField(default='2026', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Super Admin'), ('engineer', 'Field Engineer'), ('sales', 'Sales Manager'), ('observer', 'Guest Observer')], default='observer', max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.CharField(default='Admin', max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.machine')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('engineer', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='api.machine')),
            ],
        ),
    ]
