# Generated by Django 4.2.30 on 2026-08-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraccount_cancleardb_useraccount_caneditmachines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('shipDate', models.CharField(max_length=20)),
                ('carrier', models.CharField(max_length=100)),
                ('trackingNo', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='In Transit', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('docFileName', models.CharField(blank=True, default='', max_length=255)),
                ('docFileData', models.TextField(blank=True, default='')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_legs', to='api.machine')),
            ],
        ),
    ]
