# Generated by Django 4.2.30 on 2026-08-07 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shipmentleg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(db_index=True, default='System', max_length=150),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='failedLoginAttempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='isSuperAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='lastActivity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='lockoutUntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, default='ACTION', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Operations Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('sales', 'Sales & Finance Manager'), ('warehouse', 'Warehouse Manager'), ('production', 'Production Lead'), ('engineer', 'Field Engineer'), ('observer', 'Guest Observer')], default='observer', max_length=20),
        ),
    ]
